version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.envs/dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./web/
    container_name: web
    depends_on:
      - db
    env_file:
      - ./.envs/dev.env
    ports:
      - "8000:8000"
    volumes:
      - "./web/:/usr/app/"
    entrypoint: |
      uvicorn main:app --reload
  web-test:
    container_name: web-test
    build: ./web/
    entrypoint: pytest

volumes:
  db:
    driver: local

networks:
  nginx:
    external: true